export const MERMAID_THEME = {
  theme: "base",
  themeVariables: {
    background: "#fafbfc",
    primaryColor: "#e0ecff",
    primaryBorderColor: "#2563eb",
    primaryTextColor: "#0f172a",
    secondaryColor: "#f1f5f9",
    secondaryBorderColor: "#94a3b8",
    secondaryTextColor: "#0f172a",
    tertiaryColor: "#ede9fe",
    tertiaryBorderColor: "#7c3aed",
    tertiaryTextColor: "#1e1b4b",
    lineColor: "#64748b",
    textColor: "#0f172a",
    mainBkg: "#e0ecff",
    secondBkg: "#f1f5f9",
    border1: "#2563eb",
    border2: "#7c3aed",
    arrowheadColor: "#475569",
    fontFamily: "system-ui, -apple-system, 'Segoe UI', sans-serif",
    fontSize: "14px",
    clusterBkg: "#f8fafc",
    clusterBorder: "#94a3b8",
    noteBkgColor: "#fef3c7",
    noteTextColor: "#78350f",
    noteBorderColor: "#d97706",
  },
  flowchart: {
    curve: "basis",
    padding: 12,
    nodeSpacing: 40,
    rankSpacing: 50,
    useMaxWidth: true,
    htmlLabels: true,
  },
  sequence: {
    diagramMarginX: 16,
    diagramMarginY: 16,
    actorMargin: 60,
    width: 150,
    height: 50,
    boxMargin: 10,
    boxTextMargin: 5,
    noteMargin: 10,
    messageMargin: 35,
    mirrorActors: true,
    bottomMarginAdj: 1,
    useMaxWidth: true,
    rightAngles: false,
    showSequenceNumbers: false,
  },
} as const;

export const MERMAID_FONT_FAMILY =
  "system-ui, -apple-system, 'Segoe UI', sans-serif";
